/* ===== circus math ===== */
/* Batty Circus: pure maths. No DOM. The browser game (practice mode), tools/circus-sim.js and tools/circus-xcheck.js
   share it as it is. lib/games/circus.php ports it line for line, with the same order of rng() calls.

   THE REELS    5 reels x 4 rows, real reel strips. Each reel stops at a uniformly random strip position. 40 fixed lines,
                left to right from reel 1, 3+ in a row. The wild (stacked on the strips) substitutes for every pay symbol.
                The Cannonball Bat bonus symbol lands on reels 1, 3 and 5 only. One on each triggers the Cannon Bonus.
   AMOUNTS      Everything is in UNITS: 1 unit = stake / 20. Every stake on the ladder is a multiple of 20, so units are
                whole Batty Bucks.
   THE CANNON   The performer is fired at a target board of 16 segments: 5 cash prizes, the 5 acts, 5 two-act combos and
                the bullseye (three random acts). After the first shot the player may COLLECT it, or RETRY once (a fresh,
                independent shot that must be kept, which may be worse).
   THE ACTS     Played one after another in act order (Strongman, Bear, Fire Breather, Jester, Elephant).
   MAX WIN      2,500x the stake for the whole round. The round ends the moment it is reached.
   ROUND        A multi-step state machine: start() then step(state, action, choice, rng) until phase === 'done'.
                Every draw happens inside the step that needs it, after the player's choice, so nothing hidden is ever
                stored ahead of time. */
(function (root, factory) { const M = factory(); if (typeof module !== 'undefined' && module.exports) module.exports = M; (root.BattyMath = root.BattyMath || {}).circus = M; })(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  const REELS = 5, ROWS = 4, U = 20, MAX_X = 2500, CAP = MAX_X * U;

  /* symbols: index = position in this string */
  const CH = 'WELMGSAKQJB';
  const W = 0, ELE = 1, LION = 2, STRONG = 3, JUGG = 4, SEAL = 5, ACE = 6, KING = 7, QUEEN = 8, JACK = 9, BON = 10;
  const SYMBOLS = ['wild', 'elephant', 'lion', 'strongman', 'juggler', 'seal', 'ace', 'king', 'queen', 'jack', 'bonus'];
  const NAMES = ['Ringmaster Wild', 'Ellie the Elephant', 'Leo the Lion', 'Brutus the Strongbat', 'Juggling Jangles', 'Sammy the Seal', 'Ace', 'King', 'Queen', 'Jack', 'Cannonball Bat'];
  /* PAY[symbol] = [3, 4, 5 in a row], in units (1 unit = stake / 20 = two line bets) */
  const PAY = [
    [0, 0, 0],
    [25, 90, 280],  // elephant
    [20, 65, 180],  // lion
    [16, 50, 130],  // strongman
    [14, 42, 105],  // juggler
    [12, 32, 85],   // seal
    [6, 13, 32],    // ace
    [5, 11, 28],    // king
    [4, 8, 20],     // queen
    [3, 6, 16],     // jack
    [0, 0, 0],
  ];

  /* 40 fixed lines: the row (0 = top) on each reel */
  const LINES = [
    [0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3],
    [0, 1, 2, 1, 0], [3, 2, 1, 2, 3], [1, 2, 3, 2, 1], [2, 1, 0, 1, 2],
    [0, 0, 1, 0, 0], [3, 3, 2, 3, 3], [1, 1, 0, 1, 1], [2, 2, 3, 2, 2],
    [1, 1, 2, 1, 1], [2, 2, 1, 2, 2], [0, 1, 1, 1, 0], [3, 2, 2, 2, 3],
    [1, 0, 0, 0, 1], [2, 3, 3, 3, 2], [1, 2, 2, 2, 1], [2, 1, 1, 1, 2],
    [0, 1, 0, 1, 0], [3, 2, 3, 2, 3], [1, 0, 1, 0, 1], [2, 3, 2, 3, 2],
    [1, 2, 1, 2, 1], [2, 1, 2, 1, 2], [0, 1, 2, 3, 3], [3, 2, 1, 0, 0],
    [0, 0, 1, 2, 3], [3, 3, 2, 1, 0], [1, 2, 3, 3, 3], [2, 1, 0, 0, 0],
    [0, 0, 0, 1, 2], [3, 3, 3, 2, 1], [1, 0, 1, 2, 1], [2, 3, 2, 1, 2],
    [1, 2, 1, 0, 1], [2, 1, 2, 3, 2], [3, 2, 2, 1, 0], [0, 1, 1, 2, 3],
  ];

  /* reel strips (generated by tools/circus-strips.js; the same text is in lib/games/circus.php) */
  /*STRIPS*/
  const BASE = ['AKJKSESJJKABKESKGMEQMJJGQQAAJJQMJGKBAAMLQLQMLAJJJKQGSQSSAGBQSKLQKGAQKJ', 'GMAAAQSQGWWWAQSQKASKLJQSQJLMQJJGKQJMKAGALKKJJSEQSWWKAMJGAQEJKLMGEJJQKJKS', 'QLELSAAQKGQQBLQKKMJJAAAWWEGAAJKJEGQGBSMJQKJMQGMJQJSKSASWWWSLBQKMAJKKSGKJ', 'GEGQLJSQKKQAGKJWWGKAKMAJQGMGSJLQJQAJKJESMQAJAKAMJLSQQEAAJMJKJQLKQWWWWSKSS', 'WWWWKMKLSEQSBGQKQAKAAQJLKWWQQQJKJGASBKJAJAQMSGSJQGSKMGMLAQAEBJKKGSALMJEJJ'];
  const JFS = ['QJQJQAKJSJJQGJQKGLQASMGKLKJJQEMJKQKMSKAMKGEGKGAQJASAESASQJKLMAQLAJS', 'KAGEAGQGMSQQMQLMKKSGQSJWWLJJJESQAJKJMQQGAKJJAAJKSAJKAAJKGEMJLSKQQLKQS', 'MALKMJJQSEWWQJEAAQESJSGQKAQLMQJAGMGKQQKMLKJQGKAGJLSSJJJJKQAKJKSSGQAKA', 'QLQSGSGSSASKGLKJEJQMQMJEJAMKKSAKJKKAJJKGALQLJGQJQMJKQEAQAGQAJASKMJWWQ', 'AGALAQLQGQJASWWEQEJEAGJQKKLJAMKQQJAQKSSQKKSKKMJKAAJJJGJGMJMSGKSLJSMQQ'];
  const EFS = ['KALQJEJKKMQJLSGJEJBAMKAQKGAJKEMQEJAJKQJKKQKQEGQSSAAMQGESBJSQMESLJASEGJEALGQ', 'QMQQJSJQLAAKWWWQMKQEJGKGEJEQAKMQKJEGSJSASAGELSJASESLMKJJJJKKEGQAKEGAKEJLMQAQ', 'QGSSAKKKEKJMEQQAEKMBLJGQQJAJEMSAJWWWSGLAMGQGAEGESJJQEKSJQEBLMJQEKJSALAJJQAKKKQ', 'AEJSEKEQLKAEJQAJGKQKAEJMAJJQLJQKLSGSSEJGKAAJJSLSMQSAMEKMGJQQQAEKQQKMGJEKGWWW', 'ELJAGJSGMEKJAWWWAMJBQLQASSLMAGQQKGJAQAEAJJESJGEJJQJQKGKQEKBKQSLMKMKEQKJQSEKSEA'];
  /*/STRIPS*/
  const toInts = (s) => Array.from(s, (c) => CH.indexOf(c));
  const STRIPS = { base: BASE.map(toInts), jester: JFS.map(toInts), elephant: EFS.map(toInts) };

  /* ---------- the cannon board ---------- */
  const ACTS = ['strong', 'bear', 'fire', 'jester', 'elephant'];
  const ACT_NAMES = ['Brutus the Strongbat', 'Bruno on the High Wire', 'Blaze the Fire Breather', 'Jinx the Jester Spins', 'Ellie Elephant Spins'];
  /* segments 0..9 = outer ring (cash and single acts, alternating), 10..14 = middle ring (two acts), 15 = bullseye (three acts) */
  const SEGS = [
    { k: 'cash', x: 10 }, { k: 'act', a: [0] }, { k: 'cash', x: 15 }, { k: 'act', a: [1] }, { k: 'cash', x: 20 },
    { k: 'act', a: [2] }, { k: 'cash', x: 30 }, { k: 'act', a: [3] }, { k: 'cash', x: 50 }, { k: 'act', a: [4] },
    { k: 'act', a: [0, 2] }, { k: 'act', a: [1, 3] }, { k: 'act', a: [2, 4] }, { k: 'act', a: [0, 3] }, { k: 'act', a: [1, 4] },
    { k: 'bull' },
  ];
  /*BOARD*/
  const SEG_W = {
    base:      [70, 60, 60, 60, 50, 60, 30, 60, 12, 50, 26, 26, 18, 26, 18, 14],
    grand:     [0, 80, 0, 80, 0, 80, 0, 70, 0, 60, 15, 15, 11, 15, 11, 7],
    spotlight: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  };
  /*/BOARD*/
  const BUYS = { grand: 75, spotlight: 175 };

  /* ---------- act tables ---------- */
  /*ACTS*/
  /* Strongman: 8 levels. Lift chance per weight (light, medium, heavy) in percent. V[k] = the value of standing at level
     k+1, in units; the prize for a successful lift is V[k] * 100 / P - V[k+1], so every weight is worth exactly the same on
     average at every level (whatever you pick, the act is worth V[0] on average, give or take rounding). */
  const SM_P = [80, 55, 30];
  const SM_V = [1000, 1120, 1250, 1400, 1570, 1760, 1970, 2200, 0];
  /* Bear: 10 drops. Each drop, one item falls in each lane (drawn after the bear picks its lane). The anvil snaps the rope. */
  const BEAR_DROPS = 10;
  const BEAR_ITEMS = [0, 40, 80, 140, 220, 360, 540, 900, 2400];      // units; 0 = the anvil
  const BEAR_W = [16, 22, 20, 15, 11, 7, 5, 3, 1];
  /* Fire Breather: 12 torches. Each pick blasts a torch: a prize, or the fire goes out. The first blast never goes out. */
  const FIRE_TORCHES = 12;
  const FIRE_ITEMS = [0, 50, 100, 160, 250, 400, 750, 1500, 4000];     // units; 0 = out
  const FIRE_W = [48, 40, 40, 30, 20, 12, 6, 3, 1];
  /* Jester: three boxes, each holds a number of free spins; pick one. Each free spin springs 1-4 jester boxes onto
     the reels, each turning its cell wild; some explode and turn the 8 cells around them wild too. */
  const JS_SPINS = [5, 6, 7, 8, 10, 12];
  const JS_SPINS_W = [20, 26, 22, 16, 10, 6];
  const JS_N = [1, 2, 3, 4];
  const JS_N_W = [50, 32, 14, 4];
  const JS_BOOM = 0.14;
  /* Elephant: a random number of free spins at x2; every elephant that lands adds +1 to the multiplier first.
     Three bonus symbols add more spins. */
  const EL_SPINS = [7, 8, 10, 12];
  const EL_SPINS_W = [30, 30, 25, 15];
  const EL_START = 2, EL_RETRIG = 4, EL_MAX = 40;
  /*/ACTS*/

  /* ---------- helpers ---------- */
  function ri(rng, n) { const v = Math.floor(rng() * n); return v < n ? v : n - 1; }
  function pickW(rng, w) {
    let t = 0; for (let i = 0; i < w.length; i++) t += w[i];
    let v = rng() * t;
    for (let i = 0; i < w.length; i++) { v -= w[i]; if (v < 0) return i; }
    return w.length - 1;
  }
  function smPrize(level, w) { return Math.floor(SM_V[level] * 100 / SM_P[w]) - SM_V[level + 1]; }

  /* ---------- reels ---------- */
  function window_(set, stops) {
    const S = STRIPS[set], g = [];
    for (let r = 0; r < REELS; r++) { const st = S[r], L = st.length, col = []; for (let k = 0; k < ROWS; k++) col.push(st[(stops[r] + k) % L]); g.push(col); }
    return g;
  }
  function spinStops(rng, set) { const S = STRIPS[set], s = []; for (let r = 0; r < REELS; r++) s.push(ri(rng, S[r].length)); return s; }
  /* line wins on a grid, in units (before any multiplier) */
  function evaluate(g) {
    const wins = []; let pay = 0;
    for (let l = 0; l < LINES.length; l++) {
      const ln = LINES[l]; const s = [];
      for (let r = 0; r < REELS; r++) s.push(g[r][ln[r]]);
      let w = 0; while (w < REELS && s[w] === W) w++;
      let best = 0, bs = -1, bn = 0;
      if (w >= 3) { best = PAY[ELE][w - 3]; bs = ELE; bn = w; }
      if (w < REELS && s[w] !== BON) {
        const sym = s[w]; let n = w + 1;
        while (n < REELS && (s[n] === sym || s[n] === W)) n++;
        if (n >= 3 && PAY[sym][n - 3] > best) { best = PAY[sym][n - 3]; bs = sym; bn = n; }
      }
      if (best > 0) { wins.push({ l, s: bs, n: bn, pay: best }); pay += best; }
    }
    return { wins, pay };
  }
  function bonusCells(g) { const out = []; for (const r of [0, 2, 4]) for (let k = 0; k < ROWS; k++) if (g[r][k] === BON) out.push([r, k]); return out; }
  function triggered(g) { let n = 0; for (const r of [0, 2, 4]) if (g[r].indexOf(BON) >= 0) n++; return n === 3; }

  function spinBase(rng) {
    const stops = spinStops(rng, 'base'), g = window_('base', stops), e = evaluate(g);
    return { stops, grid: g, wins: e.wins, pay: e.pay, bonus: triggered(g) };
  }
  /* A bought bonus shows a trigger: a base spin with a bonus symbol put on reels 1, 3 and 5 and no line wins. */
  function buyGrid(rng) {
    let g = null, stops = null;
    for (let i = 0; i < 60; i++) {
      stops = spinStops(rng, 'base'); g = window_('base', stops);
      for (const r of [0, 2, 4]) { if (g[r].indexOf(BON) < 0) g[r][ri(rng, ROWS)] = BON; }
      if (evaluate(g).pay === 0) break;
    }
    return { stops, grid: g, wins: [], pay: 0, bonus: true, bought: true };
  }

  /* ---------- the round state machine ---------- */
  function add(s, v) {
    const before = s.total; s.total = Math.min(CAP, s.total + v);
    if (s.total >= CAP) s.capped = true;
    return s.total - before;
  }
  function start(rng, buy) {
    const b = buy ? buyGrid(rng) : spinBase(rng);
    const s = { v: 1, buy: buy || null, rev: 0, total: 0, capped: false, base: b, phase: b.bonus ? 'cannon' : 'done',
      shots: [], retried: false, queue: [], act: null, done: [], ev: { t: 'base' } };
    add(s, b.pay);
    if (s.capped) s.phase = 'done';
    return s;
  }
  function drawShot(rng, mode) {
    const seg = pickW(rng, SEG_W[mode]);
    const S = SEGS[seg];
    if (S.k === 'cash') return { seg, cash: S.x * U };
    if (S.k === 'act') return { seg, acts: S.a.slice() };
    /* bullseye: three different acts, played in act order */
    const pool = [0, 1, 2, 3, 4], got = [];
    for (let i = 0; i < 3; i++) { const j = ri(rng, pool.length); got.push(pool[j]); pool.splice(j, 1); }
    got.sort((a, b) => a - b);
    return { seg, acts: got };
  }
  function applyShot(s, shot, rng) {
    if (shot.cash) { s.ev.cash = add(s, shot.cash); s.phase = 'done'; return; }
    s.queue = shot.acts.slice();
    nextAct(s, rng);
  }
  function nextAct(s, rng) {
    s.act = null;
    if (s.capped || !s.queue.length) { s.phase = 'done'; return; }
    const a = s.queue.shift(), id = ACTS[a];
    if (id === 'strong') s.act = { id, level: 0, win: 0, log: [] };
    else if (id === 'bear') s.act = { id, drop: 0, lane: 1, win: 0, log: [] };
    else if (id === 'fire') s.act = { id, picked: [], win: 0, log: [] };
    else if (id === 'jester') s.act = { id, win: 0 };
    else s.act = { id, spins: EL_SPINS[pickW(rng, EL_SPINS_W)], win: 0 };
    s.phase = id;
  }
  function endAct(s, rng) {
    s.done.push({ id: s.act.id, win: s.act.win });
    s.ev.ended = s.act.id;
    nextAct(s, rng);
  }
  function credit(s, v) { const got = add(s, v); s.act.win += got; return got; }

  /* one free spin of the Jester act */
  function jesterSpin(rng) {
    const stops = spinStops(rng, 'jester'), g0 = window_('jester', stops);
    const g = g0.map((c) => c.slice());
    const n = JS_N[pickW(rng, JS_N_W)], used = {}, boxes = [];
    for (let i = 0; i < n; i++) {
      let c = ri(rng, 20); while (used[c]) c = (c + 7) % 20;
      used[c] = 1;
      const boom = rng() < JS_BOOM;
      boxes.push({ r: c % REELS, k: Math.floor(c / REELS), boom });
    }
    for (const b of boxes) {
      g[b.r][b.k] = W;
      if (b.boom) for (let dr = -1; dr <= 1; dr++) for (let dk = -1; dk <= 1; dk++) {
        const r = b.r + dr, k = b.k + dk; if (r >= 0 && r < REELS && k >= 0 && k < ROWS) g[r][k] = W;
      }
    }
    const e = evaluate(g);
    return { stops, grid0: g0, grid: g, boxes, wins: e.wins, pay: e.pay };
  }
  function elephantSpin(rng, mult) {
    const stops = spinStops(rng, 'elephant'), g = window_('elephant', stops);
    let el = 0; for (let r = 0; r < REELS; r++) for (let k = 0; k < ROWS; k++) if (g[r][k] === ELE) el++;
    const m = mult + el, e = evaluate(g);
    return { stops, grid: g, el, mult: m, wins: e.wins, base: e.pay, pay: e.pay * m, retrig: triggered(g) };
  }

  /* step(state, action, choice, rng) -> new state (the input is not changed). Throws on an action the phase does not allow.
     s.ev describes what just happened, for the animation. */
  function step(s0, action, choice, rng) {
    const s = JSON.parse(JSON.stringify(s0));
    const p = s.phase;
    s.ev = { t: action };
    const bad = () => { const e = new Error('That action is not available now.'); e.code = 409; throw e; };
    if (p === 'done') bad();
    else if (p === 'cannon') {
      if (action !== 'fire') bad();
      const shot = drawShot(rng, s.buy || 'base');
      s.shots.push(shot); s.ev.shot = shot;
      if (s.retried) applyShot(s, shot, rng); else s.phase = 'decide';
    } else if (p === 'decide') {
      if (action === 'collect') { s.ev.shot = s.shots[s.shots.length - 1]; applyShot(s, s.ev.shot, rng); }
      else if (action === 'retry') {
        s.retried = true;
        const shot = drawShot(rng, s.buy || 'base');
        s.shots.push(shot); s.ev.shot = shot;
        applyShot(s, shot, rng);
      } else bad();
    } else if (p === 'strong') {
      if (action !== 'pick' || !(choice >= 0 && choice <= 2)) bad();
      const a = s.act, lvl = a.level;
      const ok = rng() * 100 < SM_P[choice];
      const prize = ok ? smPrize(lvl, choice) : 0;
      const got = ok ? credit(s, prize) : 0;
      a.log.push({ w: choice, ok, prize: got });
      s.ev.lift = { level: lvl, w: choice, ok, prize: got };
      if (ok && lvl + 1 < SM_V.length - 1 && !s.capped) a.level = lvl + 1; else endAct(s, rng);
    } else if (p === 'bear') {
      if (action !== 'pick' || !(choice >= 0 && choice <= 2)) bad();
      const a = s.act, items = [];
      for (let i = 0; i < 3; i++) items.push(pickW(rng, BEAR_W));
      const it = items[choice], snap = it === 0;
      const got = snap ? 0 : credit(s, BEAR_ITEMS[it]);
      a.lane = choice; a.drop++;
      a.log.push({ lane: choice, items, got });
      s.ev.drop = { lane: choice, items, got, snap, n: a.drop };
      if (snap || a.drop >= BEAR_DROPS || s.capped) endAct(s, rng);
    } else if (p === 'fire') {
      const a = s.act;
      if (action !== 'pick' || !(choice >= 0 && choice < FIRE_TORCHES) || a.picked.indexOf(choice) >= 0) bad();
      const first = a.picked.length === 0;
      let it = pickW(rng, first ? FIRE_W.slice(1) : FIRE_W);
      if (first) it++;
      const out = it === 0, got = out ? 0 : credit(s, FIRE_ITEMS[it]);
      a.picked.push(choice); a.log.push({ t: choice, it, got });
      s.ev.blast = { t: choice, it, got, out };
      if (out || a.picked.length >= FIRE_TORCHES || s.capped) endAct(s, rng);
    } else if (p === 'jester') {
      if (action !== 'pick' || !(choice >= 0 && choice <= 2)) bad();
      const a = s.act, boxes = [];
      for (let i = 0; i < 3; i++) boxes.push(JS_SPINS[pickW(rng, JS_SPINS_W)]);
      const n = boxes[choice], spins = [];
      for (let i = 0; i < n && !s.capped; i++) {
        const sp = jesterSpin(rng); sp.got = credit(s, sp.pay); spins.push(sp);
      }
      s.ev.jester = { pick: choice, boxes, spins, win: a.win };
      endAct(s, rng);
    } else if (p === 'elephant') {
      if (action !== 'spin') bad();
      const a = s.act, spins = []; let left = a.spins, mult = EL_START, total = a.spins;
      while (left > 0 && !s.capped) {
        left--;
        const sp = elephantSpin(rng, mult); mult = sp.mult;
        if (sp.retrig && total < EL_MAX) { const add2 = Math.min(EL_RETRIG, EL_MAX - total); left += add2; total += add2; sp.extra = add2; }
        sp.got = credit(s, sp.pay); spins.push(sp);
      }
      s.ev.elephant = { spins, start: a.spins, win: a.win, mult };
      endAct(s, rng);
    } else bad();
    s.rev++;
    return s;
  }

  /* What the browser may see. Everything in the state was drawn already, so nothing is hidden. */
  function view(s) { return s; }

  /* The average value (x stake) of each board segment and of a shot, for the COLLECT / RETRY panel.
     Figures from tools/circus-sim.js. */
  /*EV*/
  const ACT_EV = [50.4, 44.7, 44.7, 59.3, 72.6];
  /*/EV*/
  function segEV(seg) {
    const S = SEGS[seg];
    if (S.k === 'cash') return S.x;
    if (S.k === 'act') { let v = 0; for (const a of S.a) v += ACT_EV[a]; return v; }
    let all = 0; for (const e of ACT_EV) all += e; return all * 3 / 5;
  }
  function shotEV(mode) { const w = SEG_W[mode]; let t = 0, v = 0; for (let i = 0; i < w.length; i++) { t += w[i]; v += w[i] * segEV(i); } return v / t; }
  function shotValueEV(shot) { if (shot.cash) return shot.cash / U; let v = 0; for (const a of shot.acts) v += ACT_EV[a]; return v; }

  function mulberry32(a) { return function () { a |= 0; a = (a + 0x6D2B79F5) | 0; let t = Math.imul(a ^ (a >>> 15), 1 | a); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }

  return {
    REELS, ROWS, U, MAX_X, CAP, CH, SYMBOLS, NAMES, PAY, LINES, STRIPS, W, ELE, LION, STRONG, JUGG, SEAL, ACE, KING, QUEEN, JACK, BON,
    ACTS, ACT_NAMES, SEGS, SEG_W, BUYS, SM_P, SM_V, smPrize, BEAR_DROPS, BEAR_ITEMS, BEAR_W, FIRE_TORCHES, FIRE_ITEMS, FIRE_W,
    JS_SPINS, JS_SPINS_W, JS_N, JS_N_W, JS_BOOM, EL_SPINS, EL_SPINS_W, EL_START, EL_RETRIG, EL_MAX, ACT_EV,
    ri, pickW, evaluate, window: window_, spinBase, buyGrid, triggered, bonusCells, jesterSpin, elephantSpin, drawShot,
    start, step, view, segEV, shotEV, shotValueEV, mulberry32,
  };
});
